# Site settings
title: Approachable
header-img: img/logoblue.svg
email: contact@approachable.tech
copyright_name: Idea Mind LLC
description: "Just Approach and Use Any Device"
baseurl: ""
url: "http://approachable.github.io"
twitter_username: IdeaMindIO
github_username:  approachable
# facebook_username:  StartBootstrap
email_username:  contact@ideamind.io

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

port: 3000

